[uhd]
env_tag = "mnist"
num_rounds = 2000
lr = 0.001
perturb = "dim:5000"
log_interval = 200
accuracy_interval = 200

enn_minus_impute = true
enn_d = 100
enn_s = 4
enn_jl_seed = 123
enn_k = 25
enn_fit_interval = 50
enn_warmup_real_obs = 200
enn_refresh_interval = 50

enn_target = "delta"
enn_num_candidates = 2

# Disable imputation: always do real negative eval.
enn_se_threshold = 0.0
