[uhd]
env_tag = "mnist_fulltrain"
num_rounds = 5000

lr = 0.001
perturb = "dim:0.5"

log_interval = 10
accuracy_interval = 50
target_accuracy = 0.50

enn_minus_impute = true
enn_target = "mu_plus"
enn_num_candidates = 10
enn_select_interval = 1

enn_embedder = "gather"
enn_gather_t = 64
enn_d = 100

enn_warmup_real_obs = 50
enn_fit_interval = 25
enn_k = 25

enn_se_threshold = 0.0
